#!/usr/bin/env bash

set -Eeuo pipefail

MAISON_HOST_IP=$(ip route show | awk '/default/ {print $3}')

for domain in ${MAISON_DOMAINS}; do
    echo "$MAISON_HOST_IP $domain" >> /etc/hosts
done

dnsmasq -d
