#!/usr/bin/env bash

set -Eeuo pipefail

dnsmasq -u root

# Launch Consul Template.
consul-template -consul-addr="$MAISON_LOCAL_IP:8500" \
    -template="/maison/web-services.ctmpl:/maison/web-services:/maison/reload" \
    -log-level=debug