#!/usr/bin/env bash

set -Eeumo pipefail

esh -o /opt/jboss/.keycloak/kcadm.config /opt/jboss/.keycloak/kcadm.config.esh

/opt/jboss/docker-entrypoint.sh -b 0.0.0.0 \
 -Djboss.bind.address=0.0.0.0 \
 -Djboss.bind.address.management=0.0.0.0 &

wait-for-it 0.0.0.0:9990
kcadm.sh config credentials --server "http://localhost:9990" --realm Maison --user "$MAISON_AUTH_ADMIN_USERNAME" --password "$MAISON_AUTH_ADMIN_PASSWORD"

fg
