#!/usr/bin/env bash

set -Eeuo pipefail

esh -o /opt/jboss/.keycloak/kcadm.config /opt/jboss/.keycloak/kcadm.config.esh

#kcadm.sh config credentials --server "http://oauth2.$MAISON_WEB_DOMAIN" --realm Maison --user "$MAISON_AUTH_ADMIN_USERNAME" --password "$MAISON_AUTH_ADMIN_PASSWORD"
kcadm.sh config credentials --server "http://localhost:8080" --realm Maison --user "$MAISON_AUTH_ADMIN_USERNAME" --password "$MAISON_AUTH_ADMIN_PASSWORD"

/opt/jboss/docker-entrypoint.sh -b 0.0.0.0
