#!/usr/bin/env bash

set -Eeuo pipefail

templates="/data/gitea/conf/app.ini"
for template in $templates; do
    envsubst < $template.envtpl > $template
done

chown "$(whoami):$(groups | awk '{ print $1 }')" -R /data

/usr/bin/entrypoint "$@"
