#!/usr/bin/env bash

set -Eeuo pipefail

mkdir -p /data/gitea/conf
envsubst < /maison/app.ini.envtpl > /data/gitea/conf/app.ini

chown "$(whoami):$(groups | awk '{ print $1 }')" -R /data

/usr/bin/entrypoint "$@"
