sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
  hosts:
    - ci.maison
    - git.maison
    - network.maison
    - ola.maison
    - hab.maison

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - cp ./travis-ci/.env ./
  - ./bin/build
  - ./bin/start
  - sleep 20
  - ./bin/provision
  - sleep 40

script:
  - ./bin/test
