sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
    - shellcheck
  hosts:
    - ci.maison
    - consul.maison
    - vcs.maison
    - network.maison
    - ola.maison
    - hab.maison

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - ./bin/build-dev
  - ./bin/start
  - ./bin/install
  - ./bin/upgrade

script:
  - ./bin/test
