sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
    - shellcheck
  hosts:
    - ci.maison
    - git.maison
    - network.maison
    - ola.maison
    - hab.maison

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - ./bin/generate-env-passwords ./travis-ci/.env > .env
  - ./bin/build
  - ./bin/start
  - ./bin/provision

script:
  - ./bin/test
