sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
  hosts:
    - maison.bartfeenstra.com

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - ./bin/build

script:
  - ./bin/test
