sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
    - apache2-utils
    - shellcheck
  hosts:
    - consul.maison

before_install:
  - sudo /etc/init.d/mysql stop

before_script:
  - ./bin/build-dev
  - ./bin/start
  - ./bin/migrate

script:
  - ./bin/test
