#!/usr/bin/env bash
# Consolidate the services' data directories into a single, top-level data directory.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

while read -r service; do
    mv "./services/$service/data" "./data/$service"
done < <(find ./services 2>/dev/null | grep '^\./services/[^/]*/data$' | sed -r 's/^\.\/services\/(.*)\/data$/\1/')
