#!/usr/bin/env bash

function install_app_db {
    local db_name=$1
    local db_username=$2
    local db_password=$3
    ./bin/await maison_db_1 3306
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS $db_name;"
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "CREATE USER IF NOT EXISTS '$db_username'@'%' IDENTIFIED BY '$db_password';"
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_username'@'%';"
    docker exec maison_db_1 mysql -u "$db_username" -p"$db_password" -D "$db_name" -e ""
}

function install_vcs_user {
    local username=$1
    local password=$2
    local email_address=$3
    ./bin/await maison_vcs_1 3000
    docker exec maison_vcs_1 /app/gitea/gitea admin create-user --name "$username" --password "$password" --email "$email_address" "${@:4}" || true
    docker exec maison_vcs_1 /app/gitea/gitea admin change-password --username "$username" --password "$password"
}
