#!/usr/bin/env bash

function install_app_db {
    local db_name=$1
    local db_username=$2
    local db_password=$3
    ./bin/await maison_db_1 3306
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS $db_name;"
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "CREATE USER IF NOT EXISTS '$db_username'@'%' IDENTIFIED BY '$db_password';"
    docker exec maison_db_1 mysql -u root -p"${MAISON_DB_ROOT_PASSWORD}" -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_username'@'%';"
    docker exec maison_db_1 mysql -u "$db_username" -p"$db_password" -D "$db_name" -e ""
}

function kcadm_init {
    ./bin/await maison_auth_1 8080
    docker exec maison_auth_1 kcadm.sh config credentials --server "http://localhost:8080/auth" --realm master --user "$MAISON_AUTH_ADMIN_USERNAME" --password "$MAISON_AUTH_ADMIN_PASSWORD"
}
