#!/usr/bin/env bash
# Test Consul.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

./vendor/bin/wait-for-it "consul.$MAISON_WEB_DOMAIN:80"
curl --verbose -f --user "$MAISON_TEST_HTTP_BASIC_AUTH_USERNAME:$MAISON_TEST_HTTP_BASIC_AUTH_PASSWORD" "$MAISON_WEB_PROTOCOL://consul.$MAISON_WEB_DOMAIN" > /dev/null
