#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./run/.env
. ./src/bash/maintenance

install_app_db "$MAISON_VCS_DB_NAME" "$MAISON_VCS_DB_USERNAME" "$MAISON_VCS_DB_PASSWORD"
install_vcs_user "$MAISON_VCS_ADMIN_USERNAME" "$MAISON_VCS_ADMIN_PASSWORD" "$MAISON_VCS_ADMIN_EMAIL" --admin
