#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./run/.env
. ./src/bash/maintenance

install_app_db "$MAISON_CI_DB_NAME" "$MAISON_CI_DB_USERNAME" "$MAISON_CI_DB_PASSWORD"
install_vcs_user "$MAISON_CI_GITEA_USERNAME" "$MAISON_CI_GITEA_PASSWORD" "$MAISON_CI_GITEA_EMAIL" --admin
