#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

old=/etc/udev/rules.d/ftdi.rules
new=/etc/udev/rules.d/maison-ola-ftdi.rules
if [ -f "$old" ] && [ ! -f "$new" ]; then
    ./vendor/krab/bin/krab stdio-inform "Moving $old to $new..."
    sudo mv "$old" "$new"
fi
