#!/usr/bin/env bash

set -Eeuo pipefail

# Parse ESH templates.
templates=(/consul/config/*.json.esh)
for template in "${templates[@]}"; do
    esh -o "${template::-4}" "$template"
done

consul agent -config-dir=/consul/config
