#!/usr/bin/env bash

set -Eeuo pipefail

# Parse ESH templates.
templates=(/consul/config/*.json.esh)
for template in "${templates[@]}"; do
    esh -o "${template::-4}" "$template"
done

consul agent -server -bootstrap -ui -config-dir=/consul/config -data-dir=/consul/data -enable-script-checks -advertise="$MAISON_LOCAL_IP" -client="$MAISON_LOCAL_IP"
