#!/usr/bin/env bash

set -Eeumo pipefail

cd "$(dirname "$0")/.."

address="$MAISON_LOCAL_IP:8500"
api_root="http://$address/v1"

# Deregister existing services.
# @todo Should we do this? It slows down booting significantly and we do not want to miss container start events
# @todo because we were still cleaning up the previous run here.
# @todo
# @todo
#while read -r service; do
#    curl -f -X PUT --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" "$api_root/agent/service/deregister/$service"
#done < <(curl -f --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" "$api_root/agent/services" | jq --unbuffered -r 'keys | join("\n")' | grep '.')

# Register services as they start.
/maison/watch
