#!/usr/bin/env bash

set -Eeuo pipefail

# Parse ESH templates.
templates=(/etc/nginx/conf.d/*.conf*.esh)
for template in "${templates[@]}"; do
    esh -o "${template::-4}" "$template"
done

# Launch nginx.
nginx -g 'daemon on;'

# Launch Consul Template.
consul-template -consul-addr="$MAISON_LOCAL_IP:8500" \
    -template="/etc/nginx/conf.d/10-consul.conf.ctmpl:/etc/nginx/conf.d/10-consul.confz:/maison/reload" \
    -log-level=debug
