#!/use/bin/env bash

# Exit on errors.
trap 'exit $?' ERR

# The Unifi controller runs on the host network. We tunnel the port dynamically so nginx can proxy to localhost.
hostip=$(ip route show | awk '/default/ {print $3}')
nc -l -p 8080 -c "nc $hostip 8080" &

# Request and renew HTTPS certificates.
for domain in ${MAISON_DOMAINS}
do
    if [ ! -d "/etc/letsencrypt/live/$domain" ]; then
    # @todo Make sure to put on a volume, so they don't get lost whenever the container reboots.
    # @todo This is necessary to prevent hitting Let's Encrypt's rate limits (https://letsencrypt.org/docs/rate-limits/)
        certbot certonly --standalone --dry-run -n --agree-tos --email bart@mynameisbart.com -d $domain
    fi
done
certbot renew

nginx -g 'daemon off;'
