#!/usr/bin/env bash

cd "$(dirname "$0")/../.." || exit

setUp() {
    maison_root=$(mktemp -d)
}

test_upgrade() {
    rsync -ra --exclude='.git' --exclude='data/*' ./ "$maison_root"
    services="db dns web"
    for service in $services; do
        mkdir -p "$maison_root/services/$service/data"
        echo "$service" | rev > "$maison_root/services/$service/data/some-data"
    done

    eval "$maison_root/migrations/1-single-data-directory"

    for service in $services; do
        test -e "$maison_root/services/$service/data"
        assertNotEquals 0 $?
        assertEquals "$(echo "$service" | rev)" "$(cat "$maison_root/data/services/$service/some-data")"
    done
}

tearDown() {
    rm -rf "$maison_root"
}

. ./vendor/shunit2/shunit2
