#!/usr/bin/env bash

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./.env

# If no explicit local IP was given, export the bridge network's gateway as the local IP, so we advertise on this host
# only.
if [ -z $MAISON_LOCAL_IP ]; then
    if ! docker network inspect maison_maison &>/dev/null; then
        docker network create maison_maison
    fi
    export MAISON_LOCAL_IP
    MAISON_LOCAL_IP=$(docker network inspect -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' maison_maison)
fi

docker-compose -p maison up --scale ci-agent=2 -d
