#!/usr/bin/env bash
# Set up shUnit2.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

. ./run/.env

address="$MAISON_LOCAL_IP:8500"
api_root="http://$address/v1"
./vendor/bin/wait-for-it "$address"
while read -r service; do
    definition=$(mktemp)
    ./vendor/bin/esh -o "$definition" "./services/$service/service.json.esh"
    curl -f -X PUT --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" --header "Content-Type: application/json" --data "@$definition" "$api_root/agent/service/register"
done < <(find ./services -type f | grep -E '^\./services/.+/service\.json\.esh$' | xargs dirname | awk -F '/' '{ print $NF }')
curl -f -X PUT --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" "$api_root/agent/reload"
