#!/usr/bin/env bash
# Register the services.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

set -a
. ./run/.env
set +a

address="$MAISON_LOCAL_IP:8500"
api_root="http://$address/v1"
./vendor/bin/wait-for-it "$address"
for service_definition_template in ./services/*/consul.json.esh; do
    service_definition=$(mktemp)
    ./vendor/bin/esh -o "$service_definition" "$service_definition_template"
    service_name=$(cat "$service_definition" | jq -r '.name')
    ./vendor/krab/bin/krab stdio-inform "Registering service '$service_name'..."
    curl -f -X PUT --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" --header "Content-Type: application/json" --data "@$service_definition" "$api_root/agent/service/register"
    rm "$service_definition"
done
./vendor/krab/bin/krab stdio-inform "Service registration complete. Reloading Consul..."
curl -f -X PUT --header "X-Consul-Token: $MAISON_CONSUL_MASTER_ACL_TOKEN_UUID" "$api_root/agent/reload"
