#!/usr/bin/env bash
# Set up shUnit2.

set -Eeuo pipefail

cd "$(dirname "$0")/.."

# Patch the E1.31 (sACN) input.
docker exec maison_ola_1 ola_patch -i -u ${MAISON_OLA_UNIVERSE} -d 1 -p 1
# Patch the output.
if [ ! -z "${MAISON_OLA_OUTPUT_DEVICE}" ] && [ ! -z "${MAISON_OLA_OUTPUT_PORT}" ]; then
    docker exec maison_ola_1 ola_patch -u ${MAISON_OLA_UNIVERSE} -d ${MAISON_OLA_OUTPUT_DEVICE} -p ${MAISON_OLA_OUTPUT_PORT}
fi
