#!/use/bin/env bash

# Exit on errors.
trap 'exit $?' ERR

templates=/etc/nginx/conf.d/*.conf.j2
for template in $templates; do
    python -c "import os
from jinja2 import Template
print Template(open('$template').read()).render(**os.environ)
" > ${template::-3}
done

hostip=$(ip route show | awk '/default/ {print $3}')
# The Unifi controller runs on the host network. We tunnel the port dynamically so nginx can proxy to localhost.
nc -l -p 8080 -c "nc $hostip 8080" &

nginx -g 'daemon off;'

