#!/use/bin/env bash

# Exit on errors.
trap 'exit $?' ERR

templates=/etc/nginx/conf.d/*.conf*.j2
for template in $templates; do
    python2 -c "
import os
from jinja2 import Template
print Template(open('$template').read()).render(**os.environ)
" > ${template::-3}
done

# The Unifi controller runs on the host network. We tunnel the port dynamically so nginx can proxy to localhost.
hostip=$(ip route show | awk '/default/ {print $3}')
socat tcp-listen:8080,reuseaddr,fork tcp:$hostip:8080 &

# Request and renew HTTPS certificates.
for domain in ${MAISON_DOMAINS}
do
    if [ ! -d "/etc/letsencrypt/live/$domain" ]; then
        command="certbot certonly --standalone -n --agree-tos --email bart@mynameisbart.com -d $domain"
        if [ ${MAISON_WEB_PROTOCOL} == 'https' ]; then
            `$command`
        else
            `$command` --dry-run || true
        fi;
    fi
done
certbot renew

nginx -g 'daemon off;'
